### ISSUE TITLE
Possibility of overwriting a python builtin?

### ISSUE THREAD

**Issue by trypsynth** [kianoosh-shakeri/pygame-easy-input#1]
Hi,
Do note that I haven't played with this library yet, but from what I understand, calling the module input will overwrite python's input() function. Might not be a huge deal because you more than likely won't need it in a pygame game, but who knows honestly.

**Comment by kianoosh-shakeri** [comment]
Hi there. Thanks for reporting that. You're right, I was completely oblivious to the fact that it may make a conflict with the input() function. I just renamed the module to pygame_easy_input. Thanks for reporting.
